### DISCUSSION TITLE
Can not build container using Dockerfile

### DISCUSSION THREAD

**Discussion by bardiakhosravi** [UnitedIncome/serverless-python-requirements#738] [General]
Trying to use a Dockerfile so that I can install [Pycairo](https://pycairo.readthedocs.io/en/latest/) on Lambda.

Using serverless-python-requirements to build.

Here the `pythonRequirements` config in `serverless.yml`

```
custom:
  pythonRequirements:
    dockerizePip: true
    dockerFile: ./Dockerfile
    useDownloadCache: false
    useStaticCache: false
```

And this is the Dockerfile

```
FROM public.ecr.aws/lambda/python:3.8

RUN yum -y install gcc cairo-devel
```

and the `pyproject.toml` is:

```
[tool.poetry]
name = "my-service-name"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.8"
pycairo = "^1.21.0"
serpy = "^0.3.1"
simplejson = "^3.17.6"
palettable = "^3.3.0"

[tool.poetry.dev-dependencies]
...

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

```

after running `sls deploy -s dev` I get the following error:

`entrypoint requires the handler name to be the first argument`

Does anyone know why? and what I have done wrong?

Thank you for your help.

**Comment by pgrzesik** [comment]
Hey @bardiakhosravi 👋 Could you please share the reproducible example with `serverless.yml` content? Are you trying to use the same Docker image as image that function uses as runtime?

**Reply by bardiakhosravi** [reply]
Thanks for the reply @pgrzesik I actually just figured it out. I was using a lambda image `public.ecr.aws/lambda/python:3.8`. And it seems like when it starts it expects an entry point to be defined and I did not define that. I foxed that by using the `amazonlinux:2` image and installing stuff myself. Now I am facing another issue whereby setting the `image` property of the function causes an error stating:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.readFile (node:fs:393:10)
    at readFile (pkg/prelude/bootstrap.js:1104:32)
    at go$readFile (/Users/bardiakhosravi/Projects/aeva-service/node_modules/graceful-fs/graceful-fs.js:118:14)
    at Object.readFile (/Users/bardiakhosravi/Projects/aeva-service/node_modules/graceful-fs/graceful-fs.js:115:12)
    at Object.readFile (/Users/bardiakhosravi/Projects/aeva-service/node_modules/universalify/index.js:5:57)
    at Object.tryCatcher (/Users/bardiakhosravi/Projects/aeva-service/node_modules/bluebird/js/release/util.js:16:23)
    at Object.ret [as readFileAsync] (eval at makeNodePromisifiedEval (/Users/bardiakhosravi/Projects/aeva-service/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
    at injectRequirements (/Users/bardiakhosravi/Projects/aeva-service/node_modules/serverless-python-requirements/lib/inject.js:23:6)
    at ServerlessPythonRequirements.injectAllRequirements (/Users/bardiakhosravi/Projects/aeva-service/node_modules/serverless-python-requirements/lib/inject.js:145:13)
    at ServerlessPythonRequirements.<anonymous> (/Users/bardiakhosravi/Projects/aeva-service/node_modules/serverless-python-requirements/index.js:219:43)
    at ServerlessPythonRequirements.tryCatcher (/Users/bardiakhosravi/Projects/aeva-service/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/bardiakhosravi/Projects/aeva-service/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/bardiakhosravi/Projects/aeva-service/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/bardiakhosravi/Projects/aeva-service/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/bardiakhosravi/Projects/aeva-service/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/bardiakhosravi/Projects/aeva-service/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/bardiakhosravi/Projects/aeva-service/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/bardiakhosravi/Projects/aeva-service/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/bardiakhosravi/Projects/aeva-service/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)
```


the `serverless.yml` file is:

```
provider:
  name: aws
  runtime: python3.8
  environment: ${file(./env.${self:custom.stage}.yml)}
  httpApi:
    shouldStartNameWithService: true
    cors: true
  ecr:
    images:
      baseimage:
        uri: <myaccount>.dkr.ecr.us-east-1.amazonaws.com/my-service-lambda@sha256:<the digest>

package:
  patterns:
    - '!node_modules/**'
...
functions:
  api:
    handler: my_service/hanlder
    image: baseimage
    layers:
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p38-numpy:7
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p38-matplotlib:10
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p38-Pillow:4
    events:
      - httpApi:
          path: /env
          method: GET

```

**Reply by pgrzesik** [reply]
You shouldn't be able to define both `handler` and `image` on a function. If you use `image`, you set handler via `entrypoint` if needed. See the example here: https://www.serverless.com/blog/container-support-for-lambda. Also, you should just set `image: <uri>` directly on function.

**Reply by bardiakhosravi** [reply]
oh thank you! this is such a big help. I will try to update the configuration.

Thanks again.

**Reply by bardiakhosravi** [reply]
unfortunately removing the `handler` field did not change anything. The updated `serverless.yml` is

```
functions:
  api:
    image:
      name: baseimage
      workingDirectory: my_service/host/api
      command:
        - handler.route
    layers:
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p38-numpy:7
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p38-matplotlib:10
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p38-Pillow:4
    events:
      - httpApi:
          path: /env
          method: GET
```

I still see the error

`The "path" argument must be of type string or an instance of Buffer or URL. Received undefined`

**Reply by bardiakhosravi** [reply]
trying to build the docker by providing a path to the dockerfile and building all requirements in the dockerfile without using serverless-python-requirements.

```
  ecr:
    images:
      apiimage:
        path: ./
```
