### DISCUSSION TITLE
Help: `dockerBuildCmdExtraArgs` usage for m1 mac docker build

### DISCUSSION THREAD

**Discussion by Treeless** [UnitedIncome/serverless-python-requirements#743] [Q&A] [answered]
Hey all, I'm trying to get this going for my **m1 mac**, and trying to have the docker image built, but i'm getting errors coming back, and can't seem to get the docker build command to use the extra args im passing below.

These are the docs I'm referencing: https://github.com/serverless/serverless-python-requirements#extra-docker-arguments

Any help would be appreciated. Thanks in advance.

---

# Code snippet in `serverless.yml`
```
...
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    dockerBuildCmdExtraArgs: ['--platform linux/arm64']
    layer: true
...
```
# Command
`sls deploy`

## More details
`which serverless`
> /opt/homebrew/bin/serverless

Installed serverless-python-requirements via node version `16.16.0`
<img width="352" alt="image" src="https://user-images.githubusercontent.com/2362454/202832610-d1261ab5-81ca-45c8-bc11-1824b3034083.png">

# Error:
> Status: Downloaded newer image for public.ecr.aws/sam/build-python3.8:latest-x86_64
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot1/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/python3/python3-124/altgraph-0.17.2-py2.py3-none-any.whl'

**Comment by Treeless** [comment]
`public.ecr.aws/sam/build-python3.8:latest-arm64` is what I need here, but its pulling down `public.ecr.aws/sam/build-python3.8:latest-x86_64`

**Comment by Treeless** [comment]
I've tried these variations:
> dockerBuildCmdExtraArgs: ['--platform linux/arm64']
> dockerBuildCmdExtraArgs: ['--platform=linux/arm64']
> dockerBuildCmdExtraArgs: ['platform=linux/arm64']
> dockerBuildCmdExtraArgs: ['--build-args', 'platform=linux/arm64']

 but no luck

**Comment by Treeless** [comment, marked as answer]
Ended up going with this code:
```
  pythonRequirements:
    dockerizePip: true
    dockerImage: public.ecr.aws/sam/build-python3.8:latest-arm64
    layer: true
```

Also downloaded manually from the website for the build image for arm.

Soon after realized my pip `requirements.txt` was malformed and had some incorrect references to the wrong python libraries for the wrong python version, after installing python3.8 through homebrew, I was able to use it to install the correct versions.

Hope this helps someone. Cheers.
