### DISCUSSION TITLE
Layer failed to create

### DISCUSSION THREAD

**Discussion by boludo00** [UnitedIncome/serverless-python-requirements#756] [Q&A]
Hi everybody, I am trying to use the lambda layer functionality within the plugin and am running into issues. It seems a straight forward process but am strangely getting this error: 

```bash
Error:
CREATE_FAILED: PythonRequirementsLambdaLayer (AWS::Lambda::LayerVersion)
Unzipped size must be smaller than 262144000 bytes (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException;
```

I am on the latest version of the plugin and my serverless version is 3.21

Here is the relevant yml:

```yml
functions:
  myfunction:
    handler: myhandler.py
    layers:
      - Ref: PythonRequirementsLambdaLayer
custom:
  pythonRequirements:
    fileName: requirements-lambda.txt
    usePoetry: false
    dockerizePip: true
    layer:
      name: MyLambdaLayer
      description: My Layer
      compatibleRuntimes:
        - python3.8
```

Nothing seems off to be but wondering if the community has any feedback of why this could be happening. My initial thought is the Ref to the layer name? 

EDIT: I think I misunderstood the concept of layers, my layer in total does exceed 250mb so this won't solve my problem. Closing this!
