### DISCUSSION TITLE
Is overriding custom pythonRequirements at function level allowed?

### DISCUSSION THREAD

**Discussion by 0aprl1** [UnitedIncome/serverless-python-requirements#805] [General]
Hello All

**SETUP**

- python: 3.8.10
- serverless: 1.80.0
- serverless-python-requirements: 5.1.0

**ISSUE**

configuration.yml is a file I use to set ```custom``` properties in serverless.yml, where I define the following noDeploy as a consequence of installing some required library that have unused sub-dependencies:

```
pythonRequirements:
  slim: false
  dockerizePip: true
  usePoetry: false
  noDeploy:
    - boto3
    - botocore
    - docutils
    - jante
    - phonenumbers
    - unidecode
    - sqlmodel
    - sqlalchemy
    - sqlalchemy-stubs
    - psycopg2
    - psycopg2_binary.libs
``` 

I have several lambdas which use the above default pythonRequirements definition. For one particular lambda I have defined, I am attempting the following:

```
test-service:
    name: function-name
    handler: service.handler.handler
    events:
      - http:
          path: /test
          method: get
          authorizer:
            name: authorizer
            resultTtlInSeconds: 3600
          cors: ${self:custom.CORS_CONFIG}
    role: ServiceLambdaExecutionRole
    custom:
      pythonRequirements:
          slim: false
          dockerizePip: true
          usePoetry: false
          noDeploy:
            - boto3
            - botocore
            - docutils
            - jante
            - phonenumbers
            - unidecode
    package: ${self:custom.SERVICE_PACKAGING} 
``` 

Basically for this function, I try to override pythonRequirements at function definition level - the two noDeploy differ in the second not having listed

```
  - sqlmodel
  - sqlalchemy
  - sqlalchemy-stubs
  - psycopg2
  - psycopg2_binary.libs 
```

When I run ```sls package --region eu-west-1 --stage stg```, I am able to package all functions correctly, except for the one defined above ```test-service```, whose zip is excluding everything (11 modules in total) as per the default pythonRequirements, while I would have expected it to exclude only the ones defined at function level (6 in total).

So my question is whether what I am attempting is allowed or not, or if I might have misconfigured something.

Thanks in advance for the support.
