### DISCUSSION TITLE
Cached packages are never cleaned up

### DISCUSSION THREAD

**Discussion by bldcaveman** [UnitedIncome/serverless-python-requirements#809] [General]
I am currently cleaning out GB's of old cached packages on my windows machine.

The files are located here:
C:\Users\[ME]\AppData\Local\UnitedIncome\serverless-python-requirements\Cache

Does anyone else have this?  Is there a command to clean these up?  I'm just deleting them for now because it seems these files are never reused.  I don't want a new one of these for every single deploy.  That's insane duplication and waste of space.

**Comment by bldcaveman** [comment]
I think this turns out to be because we use a custom package and we needed to add `invalidateCaches: true` to the custom section 

ie:
```
custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    invalidateCaches: true
```

and now it does not pile up
