### DISCUSSION TITLE
Does compatibility work with Python versions 3.10 and 3.11 or 3.12 ?

### DISCUSSION THREAD

**Discussion by cvargas-xbrein** [UnitedIncome/serverless-python-requirements#847] [Q&A]
i try to deploy a lambda with this runtime but the docker pull fail after now find the image 

`Unable to find image 'lambci/lambda:build-python3.12' locally`

**Comment by pgrzesik** [comment]
Hey @cvargas-xbrein - could you please share a sample `serverless.yml` configuration? What version of the plugin are you using? You might need to specify a custom image, the `lambci` images are no longer maintained and it's better to use official AWS images: https://gallery.ecr.aws/lambda/python

**Comment by cvargas-xbrein** [comment]
ohh, thanks for advising me, I didn't know that the lambci were obsolete, in this case I think my problem is with the serverless-python-requirements plugin because by default it will search for those images with docker


this is my servereles.yml

````
# Data Model Pipeline API
service: DataModelPipeline
frameworkVersion: ">=3.34.0"
configValidationMode: warn
provider:
  name: aws
  profile: tecnologia
  tags:
    area: datos
    deployment_type: interno
  timeout: 900
  runtime: python3.11
  versionFunctions: false
  deploymentBucket:
    name: desarrollo-datos
  environment:
    stage: ${opt:stage}
    STAGE: ${opt:stage}
    aws_region: us-east-1
 
 
 
package:
  individually: true
  patterns:
    - "!./**/*"
    - "!node_modules/**"
    - "!.requirements/**"
    - "!env/**"
    - "!README.md"
    - "!package.json"
    - "!package-lock.json"
    - "!requirements.txt"
    - .requirements.zip
    - sql_queries/**
    - utils/**

# serverless plugin install -n ...
plugins:
  - serverless-python-requirements
  - serverless-prune-plugin
  - serverless-step-functions
  - serverless-deployment-bucket
  - serverless-stage-manager 

custom: ${file(imports/custom.yml)}
functions: ${file(imports/functions.yml)}
stepFunctions: ${file(imports/step_functions.yml)}
 
 
 the custom.yml
 
 
 pythonRequirements:
  dockerizePip: non-linux
  layer: true
  zip: true
  slimPatternsAppendDefaults: false
  slimPatterns:
    - "**/*.py[c|o]"
    - "**/*.egg-info*"
    - "**/__pycache__*"
    - "**/*.dist-info*"
    - "**/dist-info*"
  useDownloadCache: true
  useStaticCache: true
  zipImport: true
prune:
  automatic: true
  number: 2
 
 
 
 
 
```






**and this is the error on docker console when execute de deploy line**


```
Unable to find image 'lambci/lambda:build-python3.11' locally
docker: Error response from daemon: manifest for lambci/lambda:build-python3.12 not found: manifest unknown: manifest unknown.
See 'docker run --help'.

```
