### DISCUSSION TITLE
Host key verification failed trying to deploy with private Github Repository

### DISCUSSION THREAD

**Discussion by james-ingold** [UnitedIncome/serverless-python-requirements#853] [Q&A]
Hello, I'm trying to serverless deploy using serverless-python-requirements, my requirements.txt contains a private repository. I've added the necessary setup options and added a new ssh key to github without a passphrase. Added the key to ssh agent. known_hosts seems to be copied over. `ssh -T git@github.com` connects successfully. 

However, I'm getting Host key verification failed when trying to deploy: 

pythonReqs serverless.yaml:
```yaml
pythonRequirements:
    useDownloadCache: false
    useStaticCache: false
    dockerizePip: non-linux
    dockerSsh: true
    dockerImage: public.ecr.aws/sam/build-python3.11:latest-arm64
    layer: true
    dockerPrivateKey: /Users/username/.ssh/github
    zip: true
```

✖ ServerlessError2: Running "docker run --rm -v /Users/username/Repos/project/project-api/.serverless/requirements:/var/task:z -v /Users/username/.ssh/github:/root/.ssh/github:z -v /Users/username/.ssh/known_hosts:/root/.ssh/known_hosts:z -v /var/folders/76/np_0fqdn7t3d45vg159_zwmh0000gn/T//ssh-JDvkgmg6oXmN/agent.19177:/tmp/ssh_sock:z -e SSH_AUTH_SOCK=/tmp/ssh_sock -u 0 public.ecr.aws/sam/build-python3.11:latest-arm64 python3.11 -m pip install -t /var/task/ -r /var/task/requirements.txt" failed with: "Running command git clone --filter=blob:none --quiet 'ssh://****@github.com/myproject/project.git' /tmp/pip-install-ruul90ya/project_8ea4e16fb3ea4a47bd5f1ec584e63d6f
  Host key verification failed.
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
  error: subprocess-exited-with-error
