### ISSUE TITLE
Python not picked up on path

### ISSUE THREAD

**Issue by kadrach** [UnitedIncome/serverless-python-requirements#100]
```
which python
/home/kadrach/.pyenv/shims/python
which python3.6
/home/kadrach/.pyenv/versions/3.6.0/bin/python3.6
```
(these refer to the same python 3.6 installation). The pyenv shim is on path, yet the serverless plugin fails to pick it up:

```
Serverless: Generating requirements.txt from Pipfile...                                                    
Serverless: Installing required Python packages with undefined...                                          
                          
  Type Error ---------------------------------------------                                                 
                          
  "file" argument must be a non-empty string         
                          
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.                   
                          
  Get Support --------------------------------------------                                                 
     Docs:          docs.serverless.com              
     Bugs:          github.com/serverless/serverless/issues                                                
     Forums:        forum.serverless.com             
     Chat:          gitter.im/serverless/serverless  
                          
  Your Environment Information -----------------------------                                               
     OS:                     linux                   
     Node Version:           8.2.0                   
     Serverless Version:     1.24.0             
```

I can *fix* this with the following directive:
```yaml
custom:
  pythonRequirements:
    pythonBin: python
```
but isn't this just referencing the same Python it should be using by default? Should this not work out of the box?

**Comment by dschep** [comment]
Yeah, that should work out of the box. My only guess is that your `PATH` env var isn't exported, if you run `node`, what's the output of `process.env.PATH`?

**Comment by dschep** [comment]
Oh wait.. i see the `Installing required Python packages with undefined...` part now. That's not right.. could you share your `serverless.yml`? It should be defaulting to your runtime

**Comment by kadrach** [comment]
Removed all pieces that didn't seem to affect the minimal example:

```yaml
---
service:
  name: foo 

frameworkVersion: ">=1.24.0"  # Only version tested

plugins:
  - serverless-python-requirements

# custom:
  # pythonRequirements:
  #   pythonBin: python

provider:
  name: aws

functions:
  dispatch:
    handler: dispatch.handler
    runtime: python3.6
```
The required python is first on path, but above example only works if I uncomment the `custom` block.
