### ISSUE TITLE
Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by OliverGavin** [UnitedIncome/serverless-python-requirements#125]
I'm new to docker so I'm not sure if I'm doing something wrong but I started docker `service docker start` and `sls deploy` and I get this:

```
$> sls deploy
Serverless: Installing required Python packages with python3.6...
Serverless: Docker Image: lambci/lambda:build-python3.6
 
  Error --------------------------------------------------
 
  Cannot connect to the Docker daemon. Is the docker daemon running on this host?

 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           9.3.0
     Serverless Version:     1.25.0

```

serverless.yml:
```
service: serverless-flask-api

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-1

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
```

I'm following this guide: https://serverless.com/blog/flask-python-rest-api-serverless-lambda-dynamodb/

**Comment by dschep** [comment]
I see you're on linux. For this to work correctly you've got to be able to run docker as yourself (IE, be in the `docker` group) or run it as root by using `sudo`.

BUT! If you're already on a 64-bit linux box, there's not as much reason to actually use docker. If the packages you're trying to use are available as `many-linux` wheels (common ones such as numpy, psycopgs2, etc are), then you don't need to use docker! You can use the `dockerizePip` option with `'non-linux'` instead of `true` and it'll only use docker on platforms where it's required to deploy (IE: macOS & Windows.. and I suppose BDSs and stuff too).

Note that if you _do_ need to compile a package there are [security implications of adding yourself to the `docker` group](https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface). So I suggest running the deploy as root, but that could very well have issues of its own.

**Comment by OliverGavin** [comment]
Ahhh...

I was wondering why this was working:

```
custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: false
```

so just by having your plugin my python packages will be packaged for Lambda and using Docker is just an  option... I assumed that ```dockerizePip: false``` disabled your module - silly me.

I am running fedora 25 64-bit :D

Thank you very much!!!
