### ISSUE TITLE
/var/task:z: No such file or directory

### ISSUE THREAD

**Issue by NakedKoala** [UnitedIncome/serverless-python-requirements#134]
Hello, I am new to serveless

I am trying to follow this tutorial:
https://serverless.com/blog/serverless-python-packaging/

But I am not able to get the docker to run 

```
venv) ➜  numpy-test serverless deploy
Serverless: Installing required Python packages with python3.6...
Serverless: Docker Image: lambci/lambda:build-python3.6
 
  Error --------------------------------------------------
 
  /bin/sh: DS/numpy-test:/var/task:z: No such file or directory
"docker run" requires at least 1 argument(s).
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container

 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           9.3.0
     Serverless Version:     1.26.0


```

This is my serverless.yml file
```
service: numpy-test



plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux


provider:
  name: aws
  runtime: python3.6

functions:
  numpy:
    handler: handler.main
```

Any help is appreciated
