### ISSUE TITLE
`exclude` does not work on dependencies

### ISSUE THREAD

**Issue by hinnerk** [UnitedIncome/serverless-python-requirements#138]
Files that are installed via `requirements.txt` can't be excluded. For example this doesn't work:

```
package:
  exclude:
    - __pycache__/**
    - pandas/tests/**
```

**Comment by dschep** [comment]
That's on purpose so that you don't have to enumerate the packages if you go with an exclude all, then include some approach that I often use:
```yaml
package:
  exclude:
    - '**/*'
  include:
    - handler.py
```

I think the best approach to what you're asking for would be to implement a plugin specific exclude option that would make your example look like:
```yaml
custom:
  pythonRequirements:
    exclude:
      - __pycache__/**
      - pandas/tests/**
```

or just a toggle to turn off the plugin's code that adds to the includes:
```yaml
custom:
  pythonRequirements:
    modifyPackageInclude: false
```
