### ISSUE TITLE
Per-function requirements does not work

### ISSUE THREAD

**Issue by ottokruse** [UnitedIncome/serverless-python-requirements#155]
I followed the [exact instructions from the docs](https://github.com/UnitedIncome/serverless-python-requirements#per-function-requirements) but it does not work. The per function requirements.txt files are not being picked up

Is this broken?

My project structure:

```
├── serverless.yml
├── contact_events_get
│      ├── requirements.txt
│      └── index.py
└── contact_events_post
       ├── requirements.txt
       └── index.py**
```

Serverless.yml excerpt:
```
`package:
  individually: true
  exclude:
    - "**/*"

functions:
  fn-contactgegevens-events-get:
    handler: contactgegevens_events_get/index.handler
    package:
        include:
          - contactgegevens_events_get/index.py
  fn-contactgegevens-events-post:
    handler: contactgegevens_events_post/index.handler
    package:
        include:
          - contactgegevens_events_post/index.py
```

It does work with a requirements.txt at top level. Also note that the docs are off because specifying the handler without the dir name doesn't do it - the lambda function still expects the file at the root level but it  is in a subir
