### ISSUE TITLE
Running a Python OpenCV Process from an AWS NodeJS Lambda Function

### ISSUE THREAD

**Issue by rjdlee** [UnitedIncome/serverless-python-requirements#167]
I have an AWS NodeJS Lambda Function that spawns Python processes, which in turn run OpenCV and other Python packaged C libraries. Any idea how I could accomplish this?

JS Function:
```
const exec = util.promisify(require('child_process').exec);
// Spawns Python process
exec(`pipenv run python scan.py`).then(// do something);
```

Python Function:
```
# scan.py
import cv2
cv2.GaussianBlur(gray, (5, 5), 0)
```

This is my serverless.yml file:
```
service: serverless

plugins:
  - serverless-webpack
  - serverless-python-requirements
provider:
  name: aws
  runtime: nodejs8.10
custom:
  webpack:
    includeModules: true

functions:
  hello:
    handler: handler.hello
```

This is my webpack.config.js:
```
const webpack = require('webpack');
const slsw = require('serverless-webpack');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const WebpackShellPlugin = require('webpack-shell-plugin');

module.exports = {
  // entry: provided by serverless
  // output: provided by serverless
  entry: slsw.lib.entries,
  target: 'node',
  externals: [
    'aws-sdk',
  ],
  mode: 'production',
  devtool: 'source-map',
  plugins: [
    new CopyWebpackPlugin([
      {
        from: '/usr/local/bin/gm',
        to: '.',
      },
    ]),
    new WebpackShellPlugin({
      onBuildEnd: ['cp -R $VIRTUAL_ENV/lib/python3.6/site-packages .webpack'],
    }),
  ],
}
```

**Comment by dschep** [comment]
That's an odd thing to do, but it should be possible by using [the `pythonBin` option](https://github.com/UnitedIncome/serverless-python-requirements#customize-python-executable) (because otherwise it defaults to your runtime, which in this case is `nodejs8.10`)

**Comment by rjdlee** [comment]
@dschep I appreciate the answer and I know it's an odd thing to do, but this is what happens when a frontend developer does full stack. 

Just gave this a shot. Seems like I'm able to execute a Python function using exec from my JS code, but my Python libraries aren't being included correctly. it seems like my Webpack configuration outputs to .serverless/service while my Python dependencies are output to .serverless/. 

This is my updated serverless.yml:
```
service: serverless
plugins:
  - serverless-webpack
  - serverless-python-requirements
provider:
  name: aws
  runtime: nodejs8.10
custom:
  webpack:
    includeModules: true
  pythonRequirements:
    pythonBin: /usr/local/bin/python3
functions:
  hello:
    handler: handler.hello
```

This is my updated Webpack configuration:
```
const webpack = require('webpack');
const path = require('path');
const slsw = require('serverless-webpack');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const PermissionsOutputPlugin = require('webpack-permissions-plugin');
const WebpackShellPlugin = require('webpack-shell-plugin');

const outputPath = path.resolve(__dirname, '.serverless');

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  externals: [
    'aws-sdk',
  ],
  mode: 'production',
  devtool: 'source-map',
  plugins: [
    new CopyWebpackPlugin([
      {
        from: '/usr/local/bin/gm',
      },
      {
        from: path.resolve(__dirname, '../document-scanner/scan.py'),
      },
    ]),
    new PermissionsOutputPlugin({
      buildFiles: [
        {
          path: path.join(outputPath, '/service/scan.py'),
          fileMode: '777',
        },
        {
          path: path.join(outputPath, '/service/gm'),
          fileMode: '777',
        },
      ],
    }),
  ],
}
```

**Comment by rjdlee** [comment]
Alright, I've gotten it to work! Here's what my files look like:

serverless.yml:
```
service: serverless

plugins:
  - serverless-python-requirements
  - serverless-webpack
provider:
  name: aws
  runtime: nodejs8.10
custom:
  pythonRequirements:
    dockerizePip: false
    pythonBin: /usr/local/bin/python3
  webpack:
    includeModules: true

package:
  individually: false
  exclude:
    - '**/*'
  include:
    - handler.js

functions:
  hello:
    handler: handler.hello
```

webpack.config.js
```
const webpack = require('webpack');
const path = require('path');
const slsw = require('serverless-webpack');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const PermissionsOutputPlugin = require('webpack-permissions-plugin');
const WebpackShellPlugin = require('webpack-shell-plugin');

const outputPath = path.resolve(__dirname, '.webpack');

module.exports = {
  // entry: provided by serverless
  entry: slsw.lib.entries,
  target: 'node',
  externals: [
    'aws-sdk',
  ],
  mode: 'production',
  devtool: 'source-map',
  plugins: [
    new CopyWebpackPlugin([
      {
        from: '/usr/local/bin/gm',
      },
      {
        from: path.resolve(__dirname, '../test/scan.py'),
      },

      // Copy pip python depnendencies from the serverless python plugin
      {
        from: path.join(__dirname, './.serverless/requirements'),
      },

      // Copy prebuilt python dependencies
      // File size was too large so I used https://github.com/aeddi/aws-lambda-python-opencv
      {
        from: path.join(__dirname, './prebuilt'),
      },

      // Not sure if needed
      {
        from: path.join(__dirname, './.serverless/requirements.txt'),
      },
    ]),

    // https://stackoverflow.com/questions/36579758/cant-get-phantomjs-to-work-on-aws-lambda/36621686#36621686
    // https://github.com/GeKorm/webpack-permissions-plugin
    new PermissionsOutputPlugin({
      buildFiles: [
        {
          path: path.join(outputPath, '/service/scan.py'),
          fileMode: '777',
        },
        {
          path: path.join(outputPath, '/service/gm'),
          fileMode: '777',
        },
      ],
    }),
  ],
};
```
