### ISSUE TITLE
Prevent plugin packaging when deploying non-python functions

### ISSUE THREAD

**Issue by icj217** [UnitedIncome/serverless-python-requirements#179]
It would be nice if the plugin could either ignore or not be invoked when deploying a non-python function. For those of us with mixed-runtime projects, this will speed up testing and deployment. 

Right now, when deploying a node function, all the python packages we have defined for our python packages get included in the node function's ZIP.

I've had to define our provider-level runtime to python3.6 and then at the function-level I repeat the runtime definitions (python3.6, node6.10, etc). Here's an example:

```yaml
service: my-mixed-runtime-service

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux
    fileName: requirements.txt

provider:
  name: aws
  runtime: python3.6
  stage: test
  region: us-east-1

functions:
  node-function:
    handler: functions/my_node_function.handler
    runtime: nodejs6.10
    timeout: 10
  python-function:
    handler: functions/my_python_function.handler
    runtime: python3.6
    timeout: 10
    package: 
      excludes: ['node_modules/']
```

Then, when running a `sls deploy --function node-function`, I get the following output. 42MB is accurate for our python packages but we would expect our node_modules to be around 9-10MB.
```
Serverless: Installing required Python packages with python3.6...
Serverless: Docker Image: lambci/lambda:build-python3.6
Serverless: Linking required Python packages...
Serverless: Packaging function: node-function...
Serverless: Excluding development dependencies...
Serverless: Unlinking required Python packages...
Serverless: Uploading function: node-function (42.49 MB)...
Serverless: Successfully deployed function: node-function
Serverless: Successfully updated function: node-function
```

And here's our requirements.txt and package.json for good measure:

**Requirements.txt**
```
appdirs==1.4.3
cached-property==1.4.0
certifi==2018.1.18
chardet==3.0.4
defusedxml==0.5.0
idna==2.6
isodate==0.6.0
lxml==4.2.1
pytz==2018.3
requests==2.18.4
requests-toolbelt==0.8.0
six==1.11.0
urllib3==1.22
zeep==2.5.0
```
**Package.json**
```json
{
  "name": "my-mixed-runtime-service",
  "version": "1.0.0",
  "description": "Blah",
  "main": "README.md",
  "dependencies": {
    "@slack/client": "^4.1.0",
    "async": "^2.6.0",
    "csv-parse": "^2.2.0",
    "detect-csv": "^1.1.0",
    "moment": "^2.22.0",
    "pg": "^7.4.1",
    "request": "^2.85.0",
    "request-promise": "^4.2.2",
    "serverless-pseudo-parameters": "^1.4.2",
    "serverless-python-requirements": "^3.3.1",
    "serverless-step-functions": "^1.4.0"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "blah"
  },
  "author": "",
  "license": "ISC",
  "homepage": "blah"
}

```

**Comment by icj217** [comment]
@bsamuel-ui Ok so I've modified my serverless.yml like so and it fixed the issue with my node.js files being packaged by the plugin. But now my python function is complaining about `No module named 'zeep'` when invoking in the Lambda console. 

Custom:
```yaml
Custom:
  pythonRequirements:
    dockerizePip: non-linux
    individually: true
```

Python Function:
```
  python-function:
    handler: functions/my_python_function/my_python_function.handler
    module: functions/my_python_function
    runtime: python3.6
    timeout: 10
    package: 
      excludes: ['node_modules/']
```

And my files look like:
```
serverless.yml
functions
   my-python-function
      py-python-function.py
```
