### ISSUE TITLE
noDeploy defaults lost when defining overrides

### ISSUE THREAD

**Issue by JBartlett86** [UnitedIncome/serverless-python-requirements#186]
Hi,

On setting some additional noDeploy overrides within my configuration I noticed my deployed package instantly began to bloat in size. It turns out that by setting an override all the core default are lost.

Defaults:
```
noDeploy: [
          'boto3',
          'botocore',
          'docutils',
          'jmespath',
          'python-dateutil',
          's3transfer',
          'six',
          'pip',
          'setuptools'
        ]
```

This means you begin to include things like boto3 within your deployment package unless you replicate the overrides defined above in your serverless yaml (in addition to your specific overrides).

This seems a bit wrong as you will never want to deploy the above libraries and it would seem to make more sense to include the noDeploy overrides specified within the serverless.yaml as an override to this list not as a replacement for it?

Thanks,
John

**Comment by petergaultney** [comment]
+1

Also, I am noticing that noDeploy doesn't appear to do anything for me (e.g. `boto` and `botocore` are in my `.requirements.zip`. Is this because I'm also using `zip: true`, or could it be related to `dockerizePip: 'non-linux'`?

**Comment by dschep** [comment]
Could you both share your relevant sections of `serverless.yml`? `noDeploy` has defaults and setting it in your config sets it, it doesn't add to it. This is because otherwise, you wouldn't be able to remove anything from it. So, if you want to not include any of the faults AND say, `flask`, your config should have:
```yaml
custom:
  pythonRequirements:
    noDeploy: 
      - boto3
      - botocore
      - docutils
      - jmespath
      - python-dateutil
      - s3transfer
      - six
      - pip
      - setuptools
      - flask
```

**Comment by Laurian** [comment]
@petergaultney I have the same issue, `zip: true` looks like it isn't affected by `noDeploy` :(

**Comment by Laurian** [comment]
OK, based on https://github.com/UnitedIncome/serverless-python-requirements/issues/138#issuecomment-366936615 I managed to remove things from `.requirements.zip` with `serverless-scriptable-plugin` like this:

```yaml
custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    noDeploy:
      - boto3
      - botocore
  scriptHooks:
    before:package:createDeploymentArtifacts:
      - "zip -d .requirements.zip boto3/* botocore/* || echo ERR: UNABLE TO REMOVE FROM ZIP"
```
