### ISSUE TITLE
Could not find a version that satisfies the requirement [...]

### ISSUE THREAD

**Issue by jasonkuhrt** [UnitedIncome/serverless-python-requirements#197]
Originally posted in #177 [here](https://github.com/UnitedIncome/serverless-python-requirements/issues/177#issuecomment-395919362).

---

I'm getting this error and I have these versions:

```json
{
  "name": "unresponsive",
  "description": "foobar",
  "license": "UNLICENSED",
  "repository": "github:dialoguemd/unresponsive",
  "version": "0.1.0",
  "dependencies": {},
  "devDependencies": {
    "serverless-pseudo-parameters": "^1.6.0",
    "serverless-python-requirements": "^4.0.3",
    "serverless-step-functions": "^1.4.1"
  }
}

```

Error exactly:

```
❯ sls deploy --stage dev
Serverless: Generating requirements.txt from Pipfile...
Serverless: Installing requirements of requirements.txt in .serverless...

  Error --------------------------------------------------

    Could not find a version that satisfies the requirement dialogue.api-client==0.0.2 (from -r .serverless/requirements.txt (line 5)) (from versions: )
No matching distribution found for dialogue.api-client==0.0.2 (from -r .serverless/requirements.txt (line 5))
```

* I am using pipenv
* I am adding support for the other index via env var: PIP_EXTRA_INDEX_URL

My serverless configuration:

```yaml
service: unresponsive
custom:
  pseudoParameters:
    allowReferences: true
provider:
  name: aws
  runtime: python3.6
  region: ca-central-1
  environment:
    state_machine_arn: ${self:resources.Outputs.UnresponsiveARN.Value}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - states:*
      Resource: "*"
functions:
  start:
    handler: unresponsive.api_start_run
    events:
      - http:
          path: /start
          method: post
  stop:
    handler: unresponsive.api_stop_run
    events:
      - http:
          path: /stop
          method: post
  state_first_nudge:
    handler: unresponsive.states_first_nudge_run
  state_second_nudge:
    handler: unresponsive.states_second_nudge_run
  state_unresponsive:
    handler: unresponsive.states_unresponsive_run
stepFunctions:
  stateMachines:
    Unresponsive:
      name: unresponsive
      definition:
        StartAt: first_nudge
        States:
          first_nudge:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-state_first_nudge
            Next: first_nudge_timeout
          first_nudge_timeout:
            Type: Wait
            SecondsPath: $.seconds_until_timeout
            Next: second_nudge
          second_nudge:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-state_second_nudge
            Next: second_nudge_timeout
          second_nudge_timeout:
            Type: Wait
            SecondsPath: $.seconds_until_timeout
            Next: unresponsive
          unresponsive:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-state_unresponsive
            End: true
resources:
  Outputs:
    UnresponsiveARN:
      Description: The ARN of the state machine.
      Value: 
        Ref: Unresponsive
plugins:
  - serverless-pseudo-parameters
  - serverless-step-functions
  - serverless-python-requirements
```
