### ISSUE TITLE
Package individually example does not work

### ISSUE THREAD

**Issue by felipe-augusto** [UnitedIncome/serverless-python-requirements#203]
Hi, I followed the documentation on how to package individually, but it seems that is not working. Here's my `serverless.yml`, closely matching the example on README:

```yml
service: test

provider:
  name: aws
  runtime: python3.6
  memorySize: 128

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    zip: true

package:
  individually: true

functions:
  func1:
    handler: index.handler
    module: function1
    events:
      - http:
          path: /func1
          method: get
  func2:
    handler: index.handler
    module: function2
    events:
      - http:
          path: /func2
          method: get
```

And here's my folder structure:
```
├── function1
│   ├── index.py
│   └── requirements.txt
├── function2
│   ├── index.py
│   └── requirements.txt
├── package.json
├── serverless.yaml
└── yarn.lock
```

When I make a request to the `func1` or `func2` I get an internal server error with the following logs on `both` functions:

```
START RequestId: 6cf2a302-702d-11e8-abcd-2f24ab6d943e Version: $LATEST
Unable to import module 'index': No module named 'index'

END RequestId: 6cf2a302-702d-11e8-abcd-2f24ab6d943e
```

I wonder what I'm doing wrong. Thanks!

**Comment by felipe-augusto** [comment]
Actually, it seem that the problem is trying to `zip: true` and package individually, has anyone managed to do it?

**Comment by felipe-augusto** [comment]
I discovered why I got the following error:

```
Unable to import module 'index': No module named 'index'
```

When I use the following config,

```yml
package:
  individually: true

functions:
  func1:
    handler: index.handler
    module: function1
    package:
      include:
        - 'function1/*.py'
```
It generates the following structure on AWS Lambda:

![image](https://user-images.githubusercontent.com/9551950/41502245-575e3d34-718c-11e8-8ea8-77935a2518e4.png)

And everything works as expected, but when using `zip: true` option, as below:

```yml
custom:
  pythonRequirements:
    zip: true

package:
  individually: true

functions:
  func1:
    handler: index.handler
    module: function1
    package:
      include:
        - 'function1/*.py'
```

It changes the folder structure to:

![image](https://user-images.githubusercontent.com/9551950/41502229-b7eda69a-718b-11e8-87bf-52dee72c1395.png)

So, I had to update my config to match the folder structure:

```yml
functions:
  func1:
    handler: function1/index.handler
    module: function1
    package:
      include:
        - 'function1/*.py'
```

But, the code that `unzip_requirements.py` fails because the piece of code below refers to the wrong path, and I throws an error that import were not found.

```js
os.environ.get('LAMBDA_TASK_ROOT', os.getcwd()), '.requirements.zip')
// Unable to import module 'function1/index': No module named 'langdetect'
```

**Comment by dschep** [comment]
aha. Good job tracking that down! Should be a relatively easy fix.

**Comment by felipe-augusto** [comment]
@dschep I think this can be closed, since #217 was merged, am I right?

**Comment by dschep** [comment]
Yup. Thanks for following up!

**Comment by babu-upcomer** [comment]
The value of `module` should in the format `/path/toindex/` and not `path.toindex`.

**Comment by BwL1289** [comment]
@dschep it seems this is broken again. after hours of debugging, I am able to confirm that turning off `zip: true` enables my code to work. here is my `serverless.yml` and `functions.yml` where the functions are executed:

```
---
service: space-debris-gui

frameworkVersion: ">=1.34 <2.0.0"

plugins:
  - serverless-python-requirements
  - serverless-plugin-split-stacks
  - serverless-offline
custom:
  #   stage: ${opt:stage, self:provider.stage}
  pythonRequirements:
    dockerizePip: true 
    # zip: true
    slim: true
    splitStacks:
      nestedStackCount: 20
      perFunction: false
      perType: false
      perGroupFunction: true

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  environment:
    MONGO_DB_NAME: ${env:MONGO_DB_NAME}
    MONGO_DB_URL: ${env:MONGO_DB_URL}
    # MONGO_COLLECTION_NAME: ${env:MONGO_COLLECTION_NAME}

package:
  individually: true
  exclude:
    - node_modules/**
    - .idea/**
    - .requirements/**
    - env/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt
    - venv/**
    - .vscode/*
    - .history/*
    - tests/*
    - .pre*
    - .post*

functions:
  - ${file(app/routes/aircrafts/functions.yml)}

resources:
  # API Gateway Errors
  - ${file(app/resources/api-gateway-errors.yml)}
```

```
---
createAircraft:
  handler: app/routes/aircrafts/handler.create_aircraft
  runtime: python3.7
  events:
    - http:
        path: aircraft
        method: post
        cors: true
        # authorizer: aws_iam

listAircrafts:
  handler: app/routes/aircrafts/handler.list_aircrafts
  runtime: python3.7
  events:
    - http:
        path: aircraft
        method: get
        cors: true
        # authorizer: aws_iam

getAircraft:
  handler: app/routes/aircrafts/handler.get_aircraft
  runtime: python3.7
  events:
    - http:
        path: aircraft/{id}
        method: get
        cors: true
        # authorizer: aws_iam

updateAircraft:
  handler: app/routes/aircrafts/handler.update_aircraft
  runtime: python3.7
  events:
    - http:
        path: aircraft/{id}
        method: put
        cors: true
        # authorizer: aws_iam

deleteAircraft:
  handler: app/routes/aircrafts/handler.delete_aircraft
  runtime: python3.7
  events:
    - http:
        path: delete-aircraft/{id}
        method: delete
        cors: true
        # authorizer: aws_iam
```
