### ISSUE TITLE
Slim functionality failing on Windows

### ISSUE THREAD

**Issue by sweepy84** [UnitedIncome/serverless-python-requirements#212]
Slim functionality not working at all on windows.
Still getting test folders >> https://snag.gy/g5SelK.jpg

Using the following options:
```
custom:
    pythonRequirements:
      slim: true
      slimPatterns:
        - "*test*"
        - "*.exe"
      pythonBin: python
      dockerizePip: true
```

Issue has been noted [here ](https://github.com/UnitedIncome/serverless-python-requirements/pull/191#issuecomment-400611590)by @dee-me-tree-or-love

**Comment by dschep** [comment]
Huh.. I thought it was supposed to work with docker @dee-me-tree-or-love ?

**Comment by sweepy84** [comment]
@dschep Nope - as per comments in #191 completely busted for windows

**Comment by dee-me-tree-or-love** [comment]
_Hey everyone, huge apologies, I have been totally out for the past months of the summer..._

Now I finally got back to look into the problem and have noticed something interesting. 
I am currently using the `"serverless-python-requirements": "^4.1.1"` version. 

While trying out to deploy I have noticed that when run with `slim: true` and `dockerizePip: true` on _Windows 10_ I have also received the error: 
> find: missing argument to `-exec'  

Then, when reviewing the console commands for package removal noticed that 
changing `` `&& find ${folderPath} -name "*.so" -exec strip {} \\;`, `` 
to `` `&& find ${folderPath} -name "*.so" -exec strip {} ;` `` 
solves the issue :thinking:. 

So I have tried to escape the semicolon using the backslashes, which appaaaarently might not be necessary... Not sure if that was the whole deal, but could someone try it out too mayube? :sweat_smile: 

_Sorry again for not keeping up for so long..._ 
Node version: `v8.11.1`
Serverless version: `1.27.3`
My `serverless.yml`
```yml
plugins:
  - serverless-python-requirements
  
custom:
  pythonRequirements:
    dockerizePip: non-linux
    # zip: true
    slim: true
```  
@sweepy84 @dschep
