### ISSUE TITLE
Unable to deploy single functions (similar to #189)

### ISSUE THREAD

**Issue by gastonrod07** [UnitedIncome/serverless-python-requirements#218]
I have the same issue as in #189. When I run `sls deploy -f one --stage dev` I get:
```
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Invoke deploy
Serverless: Invoke deploy:function
Serverless: Installing requirements of one/requirements.txt in .serverless/one...
Serverless: Docker Image: lambci/lambda:build-python3.6
Serverless: Installing requirements of two/requirements.txt in .serverless/two...
Serverless: Docker Image: lambci/lambda:build-python3.6
Serverless: Invoke package:function
Serverless: Packaging function: one...
Serverless: Excluding development dependencies...
Serverless: Injecting required Python packages to package...

  Type Error ---------------------------------------------

  path must be a string or Buffer

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: path must be a string or Buffer
    at fs.readFile (fs.js:358:11)
    at go$readFile (/Users/gaston/my-service/node_modules/graceful-fs/graceful-fs.js:73:14)
    at Object.readFile (/Users/gaston/my-service/node_modules/graceful-fs/graceful-fs.js:70:12)
    at Object.readFile (/Users/gaston/my-service/node_modules/universalify/index.js:5:67)
    at moveModuleUp (/Users/gaston/my-service/node_modules/serverless-python-requirements/lib/inject.js:58:6)
    at BbPromise.resolve.filter.map.map.func (/Users/gaston/my-service/node_modules/serverless-python-requirements/lib/inject.js:104:18)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.9.3
     Serverless Version:     1.28.0
```

serverless.yml:
```
service:
  name: my-service-name
  awsKmsKeyArn: ${file(./config-${opt:stage}.yml):awsKmsKeyArn}

provider:
  name: aws
  runtime: python3.6
  region: us-west-2
  stage: ${opt:stage}
  profile: ${opt:aws-profile}
  role: my-role
  timeout: 120
  memorySize: 128

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters

custom:
  pythonRequirements:
    dockerizePip: non-linux
  accountId: "#{AWS::AccountId}"

package:
  individually: true

resources:
  ...

functions:
  one:
    handler: main.handle
    module: ./one
    package:
      include:
      - ./one/main.py

  two:
    handler: main.handle
    module: ./two
    package:
      include:
      - ./two/main.py
```
`npm list`
```
$ npm list
├── serverless-pseudo-parameters@1.6.0
└─┬ serverless-python-requirements@4.1.0
  ├── bluebird@3.5.1
  ├─┬ fs-extra@6.0.1
  │ ├── graceful-fs@4.1.11
  │ ├─┬ jsonfile@4.0.0
  │ │ └── graceful-fs@4.1.11 deduped
  │ └── universalify@0.1.2
  ├─┬ glob-all@3.1.0
  │ ├─┬ glob@7.1.2
  │ │ ├── fs.realpath@1.0.0
  │ │ ├─┬ inflight@1.0.6
  │ │ │ ├── once@1.4.0 deduped
  │ │ │ └── wrappy@1.0.2
  │ │ ├── inherits@2.0.3
  │ │ ├─┬ minimatch@3.0.4
  │ │ │ └─┬ brace-expansion@1.1.11
  │ │ │   ├── balanced-match@1.0.0
  │ │ │   └── concat-map@0.0.1
  │ │ ├─┬ once@1.4.0
  │ │ │ └── wrappy@1.0.2 deduped
  │ │ └── path-is-absolute@1.0.1
  │ └─┬ yargs@1.2.6
  │   └── minimist@0.1.0
  ├── is-wsl@1.1.0
  ├─┬ jszip@3.1.5
  │ ├── core-js@2.3.0
  │ ├── es6-promise@3.0.2
  │ ├─┬ lie@3.1.1
  │ │ └── immediate@3.0.6
  │ ├── pako@1.0.6
  │ └─┬ readable-stream@2.0.6
  │   ├── core-util-is@1.0.2
  │   ├── inherits@2.0.3 deduped
  │   ├── isarray@1.0.0
  │   ├── process-nextick-args@1.0.7
  │   ├── string_decoder@0.10.31
  │   └── util-deprecate@1.0.2
  ├── lodash.get@4.4.2
  ├── lodash.set@4.3.2
  ├── lodash.uniqby@4.7.0
  ├── lodash.values@4.3.0
  └─┬ rimraf@2.6.2
    └── glob@7.1.2 deduped
```
