### ISSUE TITLE
Running individually packaged functions locally

### ISSUE THREAD

**Issue by Kimahriman** [UnitedIncome/serverless-python-requirements#223]
I have a Python function I'm individually packaging with requirements with a config like

```yaml
plugins:
  - serverless-python-requirements
package:
  individually: true
functions:
  hello:
    handler: handler.lambda_handler
    module: func1
```

With a file structure like

```
serverless.yml
func1/
  __init__.py
  handler.py
  requirements.txt
```

I can deploy this function and it works fine, but when I try to invoke it locally, it fails. It looks like it doesn't do anything with the `module`, and just tries to run `handler.lambda_handler` instead of `./func1.handler.lambda_handler`. If I change `handler` to `func1.handler.lambda_handler`, it runs locally, but obviously would fail when deployed.

Is there something I'm missing to make this work, or is this something that's possible to do with this plugin?
