### ISSUE TITLE
After some number of invocations, importing a module fails, and then fails for all subsequent invocations

### ISSUE THREAD

**Issue by gavinmh** [UnitedIncome/serverless-python-requirements#243]
This plugin is very helpful, thank you.

I have a Lambda function that is invoked every 30 minutes. After deployment, the function operates as expected. After some number of invocations, it fails with the following:

```
Unable to import module 'lambda_handler': No module named 'sklearn'
```

Every subsequent invocation then fails. After redeploying, it operates correctly again.

The following are my `requirements.txt`:

```
psycopg2-binary==2.7.5
SQLAlchemy==1.2.11
numpy==1.14.5
pandas==0.23.1
boto3==1.7.52
requests==2.18.4
nose==1.3.7
requests-mock==1.5.2
scikit-learn==0.19.1
scipy==1.1.0
xgboost==0.72.1
marshmallow==2.15.4
```

My `lambda_handler.py` starts with:

```
try:
    import unzip_requirements
except ImportError:
    pass
```

The following is from my `serverless.yml`:
```
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    zip: true
    dockerizePip: true
    slim: true
    noDeploy:
      - nosetests
      - requests-mock

package:
  include:
    - requirements.txt
  exclude:
    - aws-deployment*
    - .dockerignore
    - Dockerfile
    - README.md
    - .gitignore
    - venv/**
    - test/**
```

Any help is appreciated.
