### ISSUE TITLE
Module not included in the uploaded zip file

### ISSUE THREAD

**Issue by AndreaAdvanon** [UnitedIncome/serverless-python-requirements#291]
I'm new to Python so maybe I'm doing something really stupid.

I'm locally using `virtualenv`.
```bash
(venv) $ pip3 install google-cloud-vision
(venv) $ pip freeze  > requirements.txt
(venv) $ cat requirements.txt
google-api-core==1.5.2
google-auth==1.6.1
google-cloud-vision==0.35.1
googleapis-common-protos==1.5.5
protobuf==3.6.1
...
```

You can see here a directory named `protobuf`
```
(venv) $ ls -l venv/lib/python3.7/site-packages/google
total 40
drwxrwxr-x. 3 andrea andrea 4096 Nov 27 15:26 api
drwxrwxr-x. 6 andrea andrea 4096 Nov 27 15:26 api_core
drwxrwxr-x. 6 andrea andrea 4096 Nov 27 15:26 auth
drwxrwxr-x. 8 andrea andrea 4096 Nov 27 15:26 cloud
drwxrwxr-x. 3 andrea andrea 4096 Nov 27 15:26 logging
drwxrwxr-x. 3 andrea andrea 4096 Nov 27 15:26 longrunning
drwxrwxr-x. 3 andrea andrea 4096 Nov 27 15:26 oauth2
drwxrwxr-x. 7 andrea andrea 4096 Nov 27 15:26 protobuf
drwxrwxr-x. 3 andrea andrea 4096 Nov 27 15:26 rpc
drwxrwxr-x. 3 andrea andrea 4096 Nov 27 15:26 type
```

But in `.serverless/requirements` after `sls deploy`:
```
(venv) $ ls -l .serverless/requirements/google
total 36
drwxrwxr-x. 3 andrea andrea 4096 Nov 27 15:47 api
drwxrwxr-x. 6 andrea andrea 4096 Nov 27 15:47 api_core
drwxrwxr-x. 6 andrea andrea 4096 Nov 27 15:47 auth
drwxrwxr-x. 8 andrea andrea 4096 Nov 27 15:47 cloud
drwxrwxr-x. 3 andrea andrea 4096 Nov 27 15:47 logging
drwxrwxr-x. 3 andrea andrea 4096 Nov 27 15:47 longrunning
drwxrwxr-x. 3 andrea andrea 4096 Nov 27 15:47 oauth2
drwxrwxr-x. 3 andrea andrea 4096 Nov 27 15:47 rpc
drwxrwxr-x. 3 andrea andrea 4096 Nov 27 15:47 type
```

`protobuf` is not installed, causing my lambda to fail.

My `serverless.yml`:
```yaml
service: invoices

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: /usr/bin/python3
    dockerizePip: 'non-linux'

provider:
  name: aws
  runtime: python3.7

functions:
  my-function:
    handler: handler.my_handler
```
