### ISSUE TITLE
slim:true causing DistributionNotFound for werkzeug py3.7

### ISSUE THREAD

**Issue by revmischa** [UnitedIncome/serverless-python-requirements#296]
If I use `slim: true` with a project that requires Werkzeug, I get a DistributionNotFound error when importing it (py 3.7).
If I set `slim: false`, I have no problems, though my zip doubles in size.

May be similar to this?
https://github.com/Miserlou/Zappa/issues/1602

**Comment by dschep** [comment]
Yea.. seems some package need their egg-info, that makes them incompatible with the default slim options.

**Comment by revmischa** [comment]
In my mind, werkzeug is pretty basic, if you want to put flask on lambda (which I do and am encouraging people to do)

**Comment by dschep** [comment]
That's why the `slim` option is off by default 😉 
It does things that aren't part of standard python package management to try and save space but at the cost of potentially breaking something.

**Comment by dschep** [comment]
and you can always tweak `slim`'s behavior:
```yaml
custom:
  pythonRequirements:
    slim: true
    slimPatternsAppendDefaults: false
    slimPatterns:
      - "**/*.pyc"
      - "**/otherthingstoexclude
```
