### ISSUE TITLE
When using slim, .so files are being broken

### ISSUE THREAD

**Issue by ysgit** [UnitedIncome/serverless-python-requirements#318]
Issue was mentioned on thread for another issue - https://github.com/UnitedIncome/serverless-python-requirements/issues/216#issuecomment-419037475

Trying to deploy python lambda app using circleci. Build and deploy is successful but then when lambda runs we get the following error

```
Runtime.ImportModuleError: Unable to import module 'src.aws_lambda.handlers': /tmp/sls-py-req/PIL/_imaging.cpython-37m-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
```

Plugin configuration:

```yaml
custom:
  pythonRequirements:
    fileName: requirements-prod.txt
    dockerizePip: true
    zip: true
    slim: true
    useStaticCache: true
    useDownloadCache: true
    cacheLocation: './.serverless-python-cache'
```

Same serverless.yml configuration works when I run it from my own mac OS computer.

On circleci I've tried using `dockerizePip: true` with the `circleci/classic:201808-01` machine and using `dockerizePip: non-linux` using the `circleci/python:3.7-node` docker image. In the latter case the whole build takes place in the circleci docker container - originally I thought this was the cause of the issue.

I don't think I can stop using slim because the file not meet the aws lambda requirements.

**Comment by palmerabollo** [comment]
Same here:
```json
{
  "errorMessage": "Unable to import module 'handler': /opt/python/cv2/cv2.cpython-37m-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned",
  "errorType": "Runtime.ImportModuleError"
}
```

This is my `pythonRequirements` setup just in case it helps:

```yaml
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    zip: true
    layer:
      name: ${self:service}-python-requirements
      description: Python requirements lambda layer
      compatibleRuntimes:
        - python3.7
      licenseInfo: GPLv3
      allowedAccounts:
        - '*'
```
