### ISSUE TITLE
Overriding boto3 fails when zip is True

### ISSUE THREAD

**Issue by Aryik** [UnitedIncome/serverless-python-requirements#367]
Recently I found that I was using AWS services that are only available in the latest version of Boto3, but lambda had an older version. I had the following plugin configuration:

```yaml
pythonRequirements:
  dockerizePip: true
  slim: true
  zip: true
  # We want to include boto3 because lambda has an old version.
  noDeploy: []
```

However, the boto3 calls I was making were still failing. When I added a log statement to print the boto3 version, I found that the old version was being imported instead of the packaged one. 

I was able to narrow the issue down to [this line in unzip_requirements](https://github.com/UnitedIncome/serverless-python-requirements/blob/2e8117502606fd4bd82c19c3050ba0350adb2789/unzip_requirements.py#L9). Basically, when we unzip the requirements we are appending to PYTHONPATH, so AWS' version of boto3 has priority over the packaged version. I was able to fix this my rolling my own version of unzip_requirements with the following modification:
```python
# We want our path to look like [working_dir, serverless_requirements, ...] so insert instead of append
sys.path.insert(1, pkgdir)
```

Happy to submit a PR if wanted.
