### ISSUE TITLE
Can't use exclusion glob patterns in slimPatterns

### ISSUE THREAD

**Issue by mjpieters** [UnitedIncome/serverless-python-requirements#372]
Currently the `strip` option runs each pattern through `glob-all.glob.sync()` separately:

https://github.com/UnitedIncome/serverless-python-requirements/blob/f39e166e8221171ec040ca37fe0f98b6ed89ad75/lib/slim.js#L48-L52

This means we can't make use of the `glob-all` feature giving you *exclude* patterns.

Can this be updated to map all patterns to their `${folderPath}/${pattern}` form and then pass the whole list as one to `glob-all.glob.sync()`?

I realise that this requires hoisting up the `!` at the start of negation patterns pattern, e.g.

```yaml
slimPatterns:
- "**/*.dist-info*"
- "!**/specific_package.dist-info*"
```
needs to be translated (given `folderPath = "/foo/bar/"`) to

```js
patterns = [
    "/foo/bar/**/*.dist-info*",
    "!/foo/bar/**/specific_package.dist-info*"
]
```

**Comment by ptrhck** [comment]
As far as I understand, I cannot use `"!**/specific_package.dist-info*"` to exclude that folder right? Is there a workaround currently?

**Comment by Adizx12** [comment]
@ptrhck 
I have found a workaround, sadly it's a bit inconvenient to use 😞 At least it works 👍 

```
    slim: true
    slimPatternsAppendDefaults: false # we need to overwrite default dist-info
    slimPatterns:
      # "normal" exclusions:
      - '**/tests/*'
      # default dist-info with !(lib_name*) - matches only if name is not present:
      - "**/!(lib_name*)*.dist-info/*"
      # the rest of defaults:
      - '**/*.py[c|o]'
      - '**/__pycache__*'
```
