### ISSUE TITLE
Serverless Deploy fails on CircleCI with error "no such file or directory .serverless/requirements"

### ISSUE THREAD

**Issue by ajb7** [UnitedIncome/serverless-python-requirements#373]
I get:
```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Packaging Python Requirements Lambda Layer...

  Error --------------------------------------------------

  ENOENT: no such file or directory, scandir '.serverless/requirements'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     OS:                     linux
     Node Version:           6.16.0
     Serverless Version:     1.44.1

error Command failed with exit code 1.
```
My serverless.yml configs looks like:

```
custom:
  pythonRequirements:
    dockerizePip: true
    layer: true

functions:
  aFunch:
    handler: someHandler
    events:
      - s3:
          bucket: aBucket
          event: s3:ObjectCreated:*
    layers:
      - {Ref: PythonRequirementsLambdaLayer}

plugins:
  - serverless-python-requirements
```
Looks like when I `zip:true` or `layer:true` ; that is in any way requirements are zipped, the serverless deploy in CircleCI still looks for `.serverless/requirements` dir and fails to find it.

`sls deploy` on local works perfectly and so does aws lambda after deployment.

**Comment by benmcp** [comment]
Have you declared anything else in your serverless.yml file?

I had the exact same issue (using CircleCI but as a stand alone single layer/no function stack) and had to remove `individually: true` (left over code from a previous yml file).

I need more context to help you with this.

**Comment by FelschR** [comment]
Experiencing the same issue with latest serverless version and package option `individually: true` as well as `zip: true` in pythonRequirements options.
Not using CircleCI, just on a Windows machine.

**Comment by petergaultney** [comment]
we're having something that looks a lot like this as well, only on Jenkins instead of CircleCI. 

```
Serverless: Running ...
Serverless: Packaging service...
Serverless: Packaging Python Requirements Lambda Layer...
 
  Error --------------------------------------------------
 
  ENOENT: no such file or directory, scandir '.serverless/requirements'
```

**Comment by eddiecorrigall** [comment]
I am using ubuntu, I got a similar issue just now. I think my problem was my setuptools were not setup correctly or not upgraded. Here is what I ran to fix this issue:

```bash
sudo apt install python3-widgetsnbextension
sudo apt install python3-testresources
pip install --upgrade --force setuptools --user
```

I did not change my serverless.yaml, but this is what have configured:
```yaml
package:
  individually: true

custom:
  pythonRequirements:
    fileName: requirements.txt
    zip: true
    # ...

# ...
```

**Comment by aforslow** [comment]
Any updates on this? I still get this issue. I was able to get my function to run locally by setting the PYTHONPATH environment variable to each module in the serverless.yml script:

```
#serverless.yml
provider:
  environment:
    PYTHONPATH: ./function1;./function2;...
```

However, I don't know if this works in deployment, and I am also required to create a requirements.txt in the serverless.yml directory in order to deploy. To me, it would seem that the 

```
package: 
  individually: 
    true
```

option is broken somehow, because requirements.txt shouldn't be required in the serverless.yml directory if individual packaging actually worked.
