### ISSUE TITLE
Can't noDeploy numpy when pandas in requirements.txt

### ISSUE THREAD

**Issue by aaronbarzilai** [UnitedIncome/serverless-python-requirements#415]
Apologies if this is a duplicate, I tried to search for issues.  Also, I really appreciate the great work to create this plugin, I used serverless 1-2 years ago before layers and libraries like pandas on AWS was a significant pain.

I am using python and trying to use pandas on AWS Lambda.  I have managed to make everything work with a minimal requirements.text.

```
Bottleneck==1.2.1
certifi==2019.9.11
numexpr==2.7.0
numpy==1.17.2
pandas==0.25.1
python-dateutil==2.8.0
pytz==2019.3
six==1.12.0
```

However, even if I specify numpy in noDeploy option, it still seems to be appearing in .requirements.zip
![image](https://user-images.githubusercontent.com/15833991/66415142-e4087000-e9c8-11e9-883f-df156a5af073.png)

Here's my serverless.yml file section on serverless-python-requirements
```
custom:
  pythonRequirements:
    fileName: requirements.txt
    dockerizePip: true
    useStaticCache: false
    useDownloadCache: false
    zip: true # Compresses the libraries in additional file and addsunzip_requirements.py in the final bundle.
    slim: true # Removes unneeded files and directories such as *.so, *.pyc, dist-info, etc.
    noDeploy: # Omits certain packages from deployment.
      - boto3
      - botocore
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - s3transfer
      - setuptools
      - six
      - numpy
    layer: true
```

My goal is to deploy this layer without numpy to save space, and then use the built in AWS SciPy NumPy layer.  I am not a requirements.txt expert as I tend to use conda not pip.

Am I doing something wrong?

Thanks so much for all the work on this,
Aaron

**Comment by 3nomis** [comment]
did you solve it?

**Comment by littlebtc** [comment]
I got the idea. Current `noDeploy` implementation will only exclude the package from `requirements.txt` it generates. Because since `pandas` requires on `numpy`, it will added `numpy` back thus make `noDeploy` has no effect.

A fix is not so simple due to we use `pip install -t` while no corresponding uninstall command applied for that. Maybe we should add a config to explicitly exclude files from resulting Zip?

**Comment by littlebtc** [comment]
I found a very dirty workaround on that:
```yaml
    slim: true # otherwise slimPatterns will not work
    slimPatterns:
      # Won't work with noDeploy since
      # dependencies will go back
      - numpy/**
```
YMMV.
