### ISSUE TITLE
Per function requirements.txt file not included in packages

### ISSUE THREAD

**Issue by avamir10** [UnitedIncome/serverless-python-requirements#425]
I'm trying to setup per function requirements.txt files however my packages seem to not contain any requirements at all.

The important parts of the serverless.yml look like this:
```yaml
package:
  individually: true
  exclude:
    - node_modules/**
    - webservice/**
    - test/**

functions:
  change_password:
    handler: change_password_handler.handle
    module: function2
    timeout: 60
    environment:
      ENDPOINT_PATH: /rider/password/change
  get_account:
    handler: get_account_handler.handle
    module: function1
    timeout: 60
    environment:
      ENDPOINT_PATH: /rider/account/get

plugins:
  - serverless-python-requirements
  - serverless-scriptable-plugin
  - serverless-dependson-plugin
  - serverless-plugin-epsagon
  - serverless-plugin-canary-deployments
  - serverless-prune-plugin

custom:
   pythonRequirements:
       dockerizePip: true
       dockerImage: "our-base-image"
```

When trying to package using: ```sls package ```
it indeed creates a zip per each function but includes no requirements at all.
I have no requirements.txt at all in the root dir. If I do create such a file its always included in the package.

I am using the following sls version:
```
Framework Core: 1.56.1
Plugin: 3.2.1
SDK: 2.2.0
Components Core: 1.1.2
Components CLI: 1.4.0
```

The project is in Python 2.7.
The folder structure is:

function1
  -> get_account_handler.py
  -> requirements.txt
function2
   -> change_password_handler.py
   -> requirements.txt
serverless.yml

what am I missing? This feature is super cool and will be very helpful for us... would love to get it to work!

Thanks a lot!
