### ISSUE TITLE
Lambda layer is not getting created

### ISSUE THREAD

**Issue by AmitChotaliya** [UnitedIncome/serverless-python-requirements#429]
I am trying to change my python3.6 serverless application to use lambda layers.
The lambda is being created but the layer is not getting created and attached to the lambda. I am not seeing any errors.

Here's my config.

```
custom:
  pythonRequirements:
    dockerizePip: non-linux
    layer: true

functions:
  validator:
    handler: helper.validate
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
        - http:
            path: helper/validate
            method: post
```
When I run deploy I am getting the following logs.

```
Serverless: Generated requirements from /path/to/requirements.txt in /path/to/requirements.txt...
Serverless: Using static cache of requirements found at /Users/a/Library/Caches/serverless-python-requirements/7bff053d55cd1bdd1d8eb8ebdc1202b8a5fb5654fc02d8196f78f1833266dd61_slspyc ...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Packaging Python Requirements Lambda Layer...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (9.48 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
```
