### ISSUE TITLE
Error when trying to install both node and python functions simultaneously

### ISSUE THREAD

**Issue by ryancammer** [UnitedIncome/serverless-python-requirements#436]
This could be user error, but here goes: I'm trying to install the following:

```  
plugins:
  - serverless-webpack
  - serverless-stack-output
  - serverless-python-requirements

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 20

functions:
  get-training-data:
    handler: src/typescript/aws/lambda/getTrainingData.handler

  train-model:
    runtime: python3.8
    handler: src/python/aws/lambda/train_model.handler
```

And I get this error:

` Error: nodejs12.x not found! Try the pythonBin option.`

Has anyone successfully used serverless-python-requirements with a mixed language project?
