### ISSUE TITLE
passing `--no-deps` does not make any difference

### ISSUE THREAD

**Issue by grzegorzk** [UnitedIncome/serverless-python-requirements#438]
Hi,

I cannot find a way to reduce my python function size when packaging for lambda. I tried `pipCmdExtraArgs` and also `noDeploy` - none helped.

This is my serverless.yml:

```yml
# Reduce package size
package:
  individually: false
  exclude:
    - "**"
  include:
    - "./src/**"

custom:
  pythonRequirements:
    dockerizePip: non-linux
    pipCmdExtraArgs:
      - --no-deps
    zip: true
    slim: true
```

I can see the package size is the same does not matter if I have `pipCmdExtraArgs` option or not.

I also tried `noDeploy` to list all dependencies but with same effect. None of the two options makes any difference when it comes to resulting package size.

**Comment by grzegorzk** [comment]
I noticed zip files in `.serverless` folder was still there, removed them manually and redeployed and package size was down to the size I would expect.

**Comment by grzegorzk** [comment]
I thought the issue was resolved on its own by deleting `.serverless` directory, unfortunately I still face the original issue that `--no-deps` is not passed to `pip` since I can see in `.serverless` all dependencies are being installed there.

**Comment by grzegorzk** [comment]
Removing node-modules helped in a way that now package size is 1.7Mb instead of 85Mb. My latest serverless.yml:

```yml
frameworkVersion: ">=1.1.0 <2.0.0"
tenant: test
app: test

service: test

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: my-region
  versionFunctions: false
  memorySize: 128
  timeout: 30
  environment: ${file(config/env.yml)}
  iamRoleStatements: ${file(config/roles.yml)}

plugins:
  - serverless-python-requirements

# https://www.npmjs.com/package/serverless-python-requirements#optimising-packaging-time
package:
  individually: false
  include:
    - "!./**"
    - "./src/**"
  exclude:
    - "**"

custom:
  region: ${opt:region, self:provider.region}
  names:
    consumer: ${self:service}-${opt:stage, self:provider.stage}
  pythonRequirements:
    dockerizePip: true
    #dockerizePip: non-linux # does not work
    pipCmdExtraArgs:
      - --no-deps
    fileName: requirements.lambda.txt
    zip: true
    slim: true
    noDeploy:
      - package1
      - package2
      - ... # many more packages

functions:
  test:
    handler: src/test.test
    name: ${self:custom.names.consumer}
```
