### ISSUE TITLE
slimPatterns with botocore

### ISSUE THREAD

**Issue by revmischa** [UnitedIncome/serverless-python-requirements#453]
I'm trying to tell SLSPR to not package up parts of botocore because I don't need to make calls to the services. I tried:

```
  pythonRequirements:
    dockerizePip: false
    slim: true
    slimPatterns:
      # we don't need to call these services so let's not include the botocore metadata
      # it takes up a lot of space
      - "**/botocore/data/ec2/**"
      - "data/cloudfront/**"
      - "**/data/rds/**"
```

But ec2, cloudfront, and rds are all present in the package. What am I doing wrong?
Using latest plugin/serverless.

**Comment by bsamuel-ui** [comment]
Yeah, unfortunately, file globs in SPR are as horribly broken as every other tool I've seen that uses globs. I always have to hunt down the code running the glob and put print statements in.

Looking at my slim patterns file... You should drop the trailing `/**` because it will match directories correctly.

You shouldn't need to match `**/botocore` either, botocore should be at the root of your package. My slim patterns simply have entires like:

```yaml
    - botocore/data/ec2
```

`**/*.ext` works, though, as does `path/*/dir`.

(FWIW, I stuck them in a separate file because I banned a ton of crap. A lot of python modules carry tests with them, for instance.)

**Comment by revmischa** [comment]
I have exactly this
```
  pythonRequirements:
    dockerizePip: false
    slim: true
    slimPatterns:
      - botocore/data/ec2
      - botocore/data/cloudfront
      - botocore/data/rds
      - botocore/data/iam
      - botocore/data/s3
```
but I still see all of them except ec2 in the package :(

**Comment by antoniocaiazzo** [comment]
I'm trying to remove my own tests from the lambda module before deploying, I've tried every possible combination of globs but it was like `slimPatterns` was just ignored:
```
pythonRequirements:
    dockerizePip: 'non-linux'
    zip: true
    slim: true
    slimPatterns:
      - "**/*tests*"
    strip: true
```
I went to the plugin code in `index.js` and I noticed that `lib/slim.js` is never imported! Unless I'm mistaken the plugin just takes the options for slim but never uses them.

I have `"serverless-python-requirements": "^5.1.0"` in my package.json and serverless 1.64.1

**Comment by chehodgins** [comment]
This also wasn't working for me until I added `useStaticCache: false` so that the dependencies could be rebuilt:

```
pythonRequirements:
    useStaticCache: false
    dockerizePip: true
    slim: true
    slimPatterns:
      - botocore/data/ec2
```
