### ISSUE TITLE
Layers: Requirements being processed different than in non-layer mode

### ISSUE THREAD

**Issue by ffedee7** [UnitedIncome/serverless-python-requirements#485]
# Bug Report

### What did you do?
I had a deployment that worked fine. Then I added a layer for requirements.

What happened?
I tried to deploy it and the Layer was larger than 250mb
```
  An error occurred: PythonRequirementsLambdaLayer - Unzipped size must be smaller than 262144000 bytes (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 17cd4a66-de6a-4c4a-b6f5-2d9f9e79440d).
```

###  What should've happened?
It should work as before since the requirements haven't changed.

### What's the content of your serverless.yml file?

```
service: new-ubersuggest

provider:
  name: aws
  runtime: python3.6
  versionFunctions: false
  region: us-east-1
  timeout: 30

functions:
    function:
        handler: handlers.function.run
        layers:
          - {Ref: PythonRequirementsLambdaLayer}
        events:
          - http:
              method: get
              path: function
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer: true
    dockerizePip: non-linux
    slim: true
    zip: true
    useDownloadCache: true
    dockerRunCmdExtraArgs:
      ['-e', 'CFLAGS=-std=c11', '-v', '${env:PWD}:/src']
    invalidateCaches: true

```
