### ISSUE TITLE
Enabling `zip: true` causes `internal server error`

### ISSUE THREAD

**Issue by BwL1289** [UnitedIncome/serverless-python-requirements#504]
after hours of debugging, I am able to confirm that turning off zip: true enables my code to work. here is my serverless.yml and functions.yml where the functions are configured:

```
---
service: space-debris-gui

frameworkVersion: ">=1.34 <2.0.0"

plugins:
  - serverless-python-requirements
  - serverless-plugin-split-stacks
  - serverless-offline
custom:
  #   stage: ${opt:stage, self:provider.stage}
  pythonRequirements:
    dockerizePip: true 
    # zip: true
    slim: true
    splitStacks:
      nestedStackCount: 20
      perFunction: false
      perType: false
      perGroupFunction: true

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  environment:
    MONGO_DB_NAME: ${env:MONGO_DB_NAME}
    MONGO_DB_URL: ${env:MONGO_DB_URL}
    # MONGO_COLLECTION_NAME: ${env:MONGO_COLLECTION_NAME}

package:
  individually: true
  exclude:
    - node_modules/**
    - .idea/**
    - .requirements/**
    - env/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt
    - venv/**
    - .vscode/*
    - .history/*
    - tests/*
    - .pre*
    - .post*

functions:
  - ${file(app/routes/aircrafts/functions.yml)}

resources:
  # API Gateway Errors
  - ${file(app/resources/api-gateway-errors.yml)}
```

```
---
createAircraft:
  handler: app/routes/aircrafts/handler.create_aircraft
  runtime: python3.7
  events:
    - http:
        path: aircraft
        method: post
        cors: true
        # authorizer: aws_iam

listAircrafts:
  handler: app/routes/aircrafts/handler.list_aircrafts
  runtime: python3.7
  events:
    - http:
        path: aircraft
        method: get
        cors: true
        # authorizer: aws_iam

getAircraft:
  handler: app/routes/aircrafts/handler.get_aircraft
  runtime: python3.7
  events:
    - http:
        path: aircraft/{id}
        method: get
        cors: true
        # authorizer: aws_iam

updateAircraft:
  handler: app/routes/aircrafts/handler.update_aircraft
  runtime: python3.7
  events:
    - http:
        path: aircraft/{id}
        method: put
        cors: true
        # authorizer: aws_iam

deleteAircraft:
  handler: app/routes/aircrafts/handler.delete_aircraft
  runtime: python3.7
  events:
    - http:
        path: delete-aircraft/{id}
        method: delete
        cors: true
        # authorizer: aws_iam
```

screenshots of before (with `zip:true` commented out and my code working):
![Screen Shot 2020-03-29 at 1 17 04 PM](https://user-images.githubusercontent.com/17219379/77858449-e225a980-71c0-11ea-8953-be0e25d5ffbc.png)

screenshots of after (with `zip:true` not commented out and my code broken):

![Screen Shot 2020-03-29 at 1 22 13 PM](https://user-images.githubusercontent.com/17219379/77858477-25801800-71c1-11ea-9a19-bafccfdd9943.png)
