### ISSUE TITLE
invoke local issue when "module" is defined

### ISSUE THREAD

**Issue by lepirlouit** [UnitedIncome/serverless-python-requirements#520]
I'm unable to invoke my function locally when I use the module functionality:

severless.yml 
```
package:
  individually: true

functions:
  my_function:
     handler: my_function.lambda_handler
     module: src/my_function_folder
```

invoke local :
`serverless invoke local -f my_function`

got error : 
`ModuleNotFoundError: No module named 'my_function'`

**Comment by lepirlouit** [comment]
warkaround : this can be fixed in the `serverless/lib/plugins/aws/invokeLocal/invoke.py` file
by adding     
`
line 72: import os
line 73: sys.path.append(os.path.join('.', "src", "my_function_folder"))`

**Comment by jorgeandresvasquez** [comment]
Having the same issue, have you been able to find any other solutions?

**Comment by lepirlouit** [comment]
temporary try my workaround https://github.com/UnitedIncome/serverless-python-requirements/issues/520#issuecomment-638047127

**Comment by kestrelhawk** [comment]
I'm also affected by this issue. Removing the `module:` parameter works but then the plugin can't see my `requirements.txt` file as it's nested, so there's always going to be a discrepancy between the handler path determined locally and remotely. Thanks for the temporary workaround @lepirlouit!

**Comment by kestrelhawk** [comment]
I've found another temporary workaround using environment variables in `serverless.yml`: 

```yaml
functions:
  LambdaTestFunction:
    handler: ${env:HANDLER_PATH_PREFIX, ""}handler.handler
    module: src/test_lambda
  ...
  ...
package:
  individually: true
```

When I invoke locally, I use the following command: 

```bash
HANDLER_PATH_PREFIX=src/test_lambda/ LOCAL=true ./node_modules/serverless/bin/serverless.js invoke local -f LambdaTest -p ./tests/resources/base_event.yml
```

I've tested local and remote invocations and I can confirm it's working as expected.
