### ISSUE TITLE
Requirements included only in one function.zip

### ISSUE THREAD

**Issue by ptrhck** [UnitedIncome/serverless-python-requirements#525]
I am using this plugin in conjunction with https://github.com/logandk/serverless-wsgi framework to deploy a django app. I would like to deploy one function that is only for doing the migrations.

So my serverless.yaml looks roughly like this:

```
service: django

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-stage-manager
  - serverless-domain-manager
  - serverless-plugin-warmup
  - '@jimdo/serverless-dotenv'

custom:
  wsgi:
    app: django_core.wsgi.application
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    zip: true # use if zip file is too big, e.g. with numpy etc.
    slim: true
    noDeploy:
      - awscli
  stage: ${opt:stage, self:provider.stage}
 
package:
  individually: true
  exclude:
    - '**'

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage,'staging'}
  region: eu-central-1
 
functions:
  api:
    handler: wsgi_handler.handler
    package:
      include:
        - '!./**'
        - './django_core/**'
        - './app1/**'
        - './app2/**'
        - './wsgi_handler.py'
        - './serverless_wsgi.py'
        - './.serverless-wsgi'
        - '!./*/migrations/**'
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    logs:
      restApi: true
    memorySize: 3008
    warmup:
      enabled: prod
  migrate:
    handler: migrate.handler
    package:
      include:
        - '!./**'
        - './*/migrations/**'
        - './migrate.py'
        - './manage.py'
    memorySize: 512
    warmup:
      enabled: false
```

In the migrate.zip file, there is no .requirements.zip included. It is only included in the api.zip. However, adding `'./.requirements.zip'` to the include in the migrate function it works. Am I missing something on this?

I would prefer to only have django as a dependcy for the migrate function. How can this be achieved? Using the module and vendor option at the function level with a own requirements.txt did not work.
