### ISSUE TITLE
serverless package with pythonRequirements layer is requiring valid aws credentials

### ISSUE THREAD

**Issue by herbaltealeaf** [UnitedIncome/serverless-python-requirements#530]
## Expected
Running `serverless package` to make re-useable deployment artifacts (zipped requirement.txt assets) without needing aws credentials.

## Behavior
The serverless-python-requirements plugin when running `serverless package` and NO aws credentials are present, works  WITHOUT layers but not WITH layers.

Not supplying aws credentials will fail the serverless package command when using a serverless-python-requirements layer (`.custom.pythonRequirements.layer`). 
```
serverless package --conceal --package "./my_package_dir"
```

### Example yaml
```
service: report-generator
plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-offline-python
  - serverless-prune-plugin

provider:
  name: aws
  runtime: python3.6
  versionFunctions: false
  memorySize: 256
  timeout: 900
  stage: ${env:ENVIRONMENT}
  region: us-east-1

functions:
  generate_data_file:
    handler: handler.generate_data_file
    layers:
      - Ref: PythonRequirementsLambdaLayer

custom:
  pythonRequirements:
    dockerizePip: true
    slim: false
    layer:
      name: ${self:provider.stage}-PythonRequirementsLambdaLayer
      description: Python Requirements some Service
      compatibleRuntimes:
        - python3.6
      allowedAccounts:
        - '*'
    useDownloadCache: true
    useStaticCache: true
    staticCacheMaxVersions: 10
    cacheLocation: ./.serverless-python-requirements
```

### Output of error
```
Serverless: DOTENV: Loading environment variables from .env:
Serverless:      - ENVIRONMENT
Serverless: Generated requirements from /home/user/Repos/report-generator/requirements.txt in /home/user/Repos/report-generator/.serverless/requirements.txt...
Serverless: Installing requirements from /home/user/Repos/report-generator/.serverless-python-requirements/61b3e00a6dc888536229a7a64d648eec28e1f0d8c0e07da557f95f5373ea0bb7_slspyc/requirements.txt ...
Serverless: Using download cache directory /home/user/Repos/report-generator/.serverless-python-requirements/downloadCacheslspyc
Serverless: Running ...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Packaging Python Requirements Lambda Layer...

 
  Serverless Error ---------------------------------------
 
  Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.18.2
     Framework Version:         1.74.1
     Plugin Version:            3.6.15
     SDK Version:               2.3.1
     Components Version:        2.31.12
```

### "Working" YAML
```
service: report-generator
plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-offline-python
  - serverless-prune-plugin

provider:
  name: aws
  runtime: python3.6
  versionFunctions: false
  memorySize: 256
  timeout: 900
  stage: ${env:ENVIRONMENT}
  region: us-east-1

functions:
  generate_data_file:
    handler: handler.generate_data_file
    layers:
      - Ref: PythonRequirementsLambdaLayer

custom:
  pythonRequirements:
    dockerizePip: true
    slim: false
    useDownloadCache: true
    useStaticCache: true
    staticCacheMaxVersions: 10
    cacheLocation: ./.serverless-python-requirements
```

### Output
```
Serverless: DOTENV: Loading environment variables from .env:
Serverless:      - ENVIRONMENT
Serverless: Generated requirements from /home/user/Repos/report-generator/requirements.txt in /home/user/Repos/report-generator/.serverless/requirements.txt...
Serverless: Using static cache of requirements found at /home/user/Repos/report-generator/.serverless-python-requirements/61b3e00a6dc888536229a7a64d648eec28e1f0d8c0e07da557f95f5373ea0bb7_slspyc ...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Injecting required Python packages to package...
```
