### ISSUE TITLE
Unable to import module 'handler': jsonschema when using usePoetry: true

### ISSUE THREAD

**Issue by MarwanDebbiche** [UnitedIncome/serverless-python-requirements#555]
Hi everyone,

Not sure if this is a [jsonschema](https://github.com/Julian/jsonschema) issue, a `poetry` issue, or a `serverless-python-requirements` issue, but I get the following error when invoking a Lambda that imports jsonschema after deploying it using serverless-python-requirements with `usePoetry: true`:

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'handler': jsonschema
```

Here is my `serverless.yml`:

```yaml
service: test-poetry-serverless
provider:
  name: aws
  runtime: python3.8
  region: eu-west-3

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET /hello

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    usePoetry: true

```

`pyproject.toml`
```toml
[tool.poetry]
name = "test-poetry-serverless"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.8"
jsonschema = "^3.2.0"

[tool.poetry.dev-dependencies]
pylint = "^2.6.0"
pycodestyle = "^2.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

```

`handler.py`
```python
import json
import jsonschema


def hello(event, context):
    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": "Hello from AWS Lambda !"
        })
    }
```

If i use `usePoetry: false` and the following *requirements.txt*, then everything works fine:

```
jsonschema==3.2.0
```

But I would really like to use poetry.

I noticed that when using poetry, there is no `jsonschema-3.2.0.dist-info` directory in `.serverless/requirements` (only a `jsonschema` directory), while both are generated when using pip. Maybe the problem comes from there ?

I also tested locally using `poetry run serverless offline` and everything works fine.

**python:** 3.8.5
**Poetry:** 1.0.10
**serverless-python-requirements:** 5.1.0

Thank you for your help !
