### ISSUE TITLE
Question: When using layer is noDeploy option respected?

### ISSUE THREAD

**Issue by tgjorgoski** [UnitedIncome/serverless-python-requirements#577]
I ask because I have the following configuration, which works fine:

```
custom:
  pythonRequirements:
    useStaticCache: false # set to false, to force update
    noDeploy:
      - botocore
      - boto3
      - botostubs
      - typing # imorted from a specific library creates issues with python3.8 
    dockerizePip: true
    slim: true
    strip: false
```

And things work fine, however if I add
```layer: true```
It seems that I'm getting the error from the typing library.
