### ISSUE TITLE
Lambda resolutely refuses to run: Unable to import module

### ISSUE THREAD

**Issue by akzincsystems** [UnitedIncome/serverless-python-requirements#579]
### Context: 
I'm trying to do a comparison of running Lambdas using PHP (our current method), Golang and Python3. I have the PHP and Golang (zero to running app in 3 hrs!)  lambdas running fine, so now it's the turn of Python. Although I do use Python from time to time, I'm no Pythonista, so please bear with me.  I've followed the details in your (rather good, wish others were as effective) plugin page but my Lambda resolutely refuses to run. It is also majorly important that we can run Python in it's own environment to take advantage of the excellent 3rd party libs out there. These aren't plain vanilla functions.  I'm testing a cognito logon workflow in this case.

Error: **Lambda execution failed with status 200 due to customer function error: Unable to import module 'api-logon-lambda': jsonschema**

### Here's what I do know:  
- The function runs locally just fine, given my aws credentials
- I'm using pipenv  cached into my user directory (tried doing it as a local to project but that went belly up quickly), but dependency management is important, right!
- I'm using strict typing backed by mypi (cannot afford to lose strict typing for my devs - they'd crucify me). Running mypi passes validation
- The function is in the root of my directory (no modules, packages etc just yet - KISS)

Therefore it seems that it is something to do with my serverless config perhaps?

### My (essential) file layout
 - schema
   - logon_cognito.json //refered to in the lamda function - works fine locally
 - api-logon-lambda.py
 - Pipfile

### Content of Pipfile
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
jwt = "*"
boto3 = "*"
jsonschema = "*"
pyjwt = "*"

[dev-packages]

[requires]
python_version = "3.8"
```
### My (essential) serverless config
```yaml
service: apilogon-srvc-py

plugins:
  - serverless-python-requirements

custom:
  env: ${env:SLS_ENV, development}
  version: ${env:SVERSION, '0.0.0'}
  environment: ${file(./serverless/env/${self:custom.env}.yml)}
  logRetentionDays: 7
  pythonRequirements:
    dockerizePip: non-linux
    noDeploy:
      - pytest
    invalidateCaches: true

provider:
  name: aws
  runtime: python3.8
  region: eu-west-2
  stage: poc
  vpc:
    securityGroupIds: ${self:custom.environment.vpc.securityGroupIds}
    subnetIds: ${self:custom.environment.vpc.subnetIds}
  apiGateway:
    restApiId: ${self:custom.environment.apiGateway.restApiId}
    restApiRootResourceId: ${self:custom.environment.apiGateway.restApiRootResourceId}

functions:
  logonhandler:
    handler: api-logon-lambda.logon
    description: 'API Logon Service Worker'
    tags:
      Name: "API Logon Service Worker"
      App_Role: "Service Worker"
      OS_Version: "Python 3.8"

    environment:
      ENVIRONMENT: ${self:custom.env}
      COGNITO_POOL_ID: ${self:custom.environment.cognito.pool_id}
      COGNITO_CLIENT_ID: ${self:custom.environment.cognito.client_id}
      REDIS_HOST: ${self:custom.environment.elasticCache}
      ALB_DNS: ${self:custom.environment.albDns}
      APIGWID: ${self:custom.environment.apiGateway.restApiId}

    events:
      - http:
          method: post
          path: py/api/logon
          request:
            schema:
              application/json: ${file(schema/logon_cognito.json)}
          cors:
            origin: '*'
            headers: '*'

package:
  exclude:
    - .idea/**
    - ./*.iml
    - package**
    - node_modules/**
    - serverless/**
    - Makefile
    - README.md
    - .mypy_cache/**
    - docs/**

```
This config, with alterations for the particular language being used, works. The key difference is in the pythonRequirements and function handler declarations. My package.excludes reflect my dev environment

### My function imports
```python
import os
import base64
import json
import logging
import boto3
import botocore.exceptions
from http import HTTPStatus
from jsonschema import validate as jVal
from jsonschema.exceptions import ValidationError
import pathlib
import copy
from typing import Dict, Optional, TypedDict, Tuple, Any
import jwt
```

Any help appreciated. This is days out of my life :-(
