### ISSUE TITLE
Deploy fails when application contains container image

### ISSUE THREAD

**Issue by AgDude** [UnitedIncome/serverless-python-requirements#585]
serverless framework and aws lambda have added support for customer containers.  When running a custom container a "runtime" property is not required, which causes the deploy to fail.

Example serverless.yml with container function:
```
functions:
  somePythonFunction:
    runtime: python3.6
    handler: handler.do_stuff
  someFunction:
    image: <account>.dkr.ecr.<region>.amazonaws.com/<repository>:<tag>
```

The work
