### ISSUE TITLE
Reference nested pyproject.toml

### ISSUE THREAD

**Issue by cthomaschase** [UnitedIncome/serverless-python-requirements#608]
I have a serverless project where `pyproject.toml` is nested inside a subfolder.

Is there a way to indicate the path to `pyproject.toml` when using 

```
  pythonRequirements:
    dockerizePip: true
    usePoetry: true
    layer: true
```

When it's in the root, everything works fine, otherwise I get error 

`ENOENT: no such file or directory, scandir '.serverless/requirements']`
