### ISSUE TITLE
Django SQS

### ISSUE THREAD

**Issue by SHELA** [UnitedIncome/serverless-python-requirements#637]
Hello,
Tried to use Django + Sqs. 
handler set as manage.py + command name
Got from Lambda - 
` [ERROR] Runtime.HandlerNotFound: Handler 'parsing' missing on module 'manage' Traceback (most recent call last): `
```
functions:
  queue:
    handler: manage.parsing
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:*****:Parser
          batchSize: 1
```

What handler should be in django?
Thank You
