### ISSUE TITLE
`sls deploy` not packaging requirements.txt

### ISSUE THREAD

**Issue by chasebleyl** [UnitedIncome/serverless-python-requirements#79]
When I run `sls deploy` it does not appear to be packaging up my requirements. I expect:

```
Serverless: Parsing Python requirements.txt
Serverless: Installing required Python packages for runtime python3.6...
```

But instead am seeing:

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (18.01 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
```

My serverless.yml looks as follows:

```
service: ...
provider:
  name: aws
  runtime: python3.6

  stage: dev
  region: ...

  environment:
    ...

  plugins:
    - serverless-python-requirements

  custom:
    pythonRequirements:
      dockerizePip: true

  iamRoleStatements:
    ...
functions:
  ...
```

Any idea where I could be going wrong here?

**Comment by dschep** [comment]
I don't think that `serverless.yml` is setup quite right. AFAICT it should be:
```yaml
service: ...
provider:
  name: aws
  runtime: python3.6

  stage: dev
  region: ...

  environment:
    ...

  iamRoleStatements:
    ...

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
functions:
  ...
```

Namely: `plugins` and `custom` are top level options, not options under `provider`
