### ISSUE TITLE
unable to deploy on serverless v4

### ISSUE THREAD

**Issue by smorgsborgs** [UnitedIncome/serverless-python-requirements#861]
### Are you certain it's a bug?

- [x] Yes, it looks like a bug

### Are you using the latest plugin release?

- [x] Yes, I'm using the latest plugin release

### Is there an existing issue for this?

- [x] I have searched existing issues, it hasn't been reported yet

### Issue description

In the process of upgrading our repos from serverless v3 to v4, we have been unable to deploy our python stacks. The plugin is installed, but is not being found when sls deploy runs.

We did not have issues with this plugin on  serverless v3, and made no changes other than bumping the version of serverless framework installed in our gitlab deploy runner.

### Service configuration (serverless.yml) content

```yaml
useDotenv: true
dashboard:
  disableMonitoring: true

provider:
  name: aws
  runtime: python3.10
  kmsKeyArn: ${ssm:/lambda/kmsKeyArn}
  tags:
    env: ${opt:stage, self:provider.stage}
    sls-app: ${self:app}
    sls-service: ${self:service}
  stage: ${opt:stage, env:STAGE}
  region: us-east-2
  deploymentBucket: #redacted

  iamRoleStatements: #redacted

  environment: #redacted

  vpc:
    securityGroupIds:
      - #redacted
    subnetIds:
      - #redacted

# you can add packaging information here
package:
  exclude:
    - env/**
    - node_modules/**

functions:
  name_update:
    handler: handler.name_update
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - PersonQ
              - Arn

resources:
  Resources:
    PersonQ:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:service}-${self:provider.stage}
        RedrivePolicy:
            deadLetterTargetArn: !GetAtt
              - PersonDlq
              - Arn
            maxReceiveCount: 10
    PersonDlq:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: ${self:service}-${opt:stage, self:provider.stage}-PersonDlq
    PersonQueueSqsPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - Ref: PersonQ
        PolicyDocument:
          Version: "2008-10-17"
          Statement:
            - Sid: "allow-sns-messages"
              Effect: Allow
              Principal: "*"
              Resource: !GetAtt
                - PersonQ
                - Arn
              Action:
                - "sqs:SendMessage"
                - "sqs:ReceiveMessage"
              Condition:
                ArnEquals:
                  "aws:SourceArn": ${env:TOPICARN}
    PersonSubscription:
      Type: "AWS::SNS::Subscription"
      Properties:
        TopicArn: ${env:TOPICARN}
        Endpoint: !GetAtt
          - PersonQ
          - Arn
        Protocol: sqs
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
```

### Command name and used flags

sls deploy --stage sls-v4

### Command output

```shell
$ npm i -g serverless@4
added 71 packages in 4s
20 packages are looking for funding
  run `npm fund` for details
$ npm i -g serverless-python-requirements@6.1.2
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated lodash.get@4.4.2: This package is deprecated. Use the optional chaining (?.) operator instead.
npm warn deprecated appdirectory@0.1.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
added 98 packages in 4s
7 packages are looking for funding
  run `npm fund` for details
$ npm i -g serverless-wsgi
added 26 packages in 2s
$ npm i -g serverless-domain-manager
added 390 packages in 18s
23 packages are looking for funding
  run `npm fund` for details
$ cd $persons_dir
$ sls deploy -s $DEPLOY_STAGE
✔ Installed Serverless Framework v4.14.3
Disable auto-updates by adding "frameworkVersion" to your serverless.yml (frameworkVersion: ~4.14.3)
✖ ServerlessError2: Serverless plugin "serverless-python-requirements" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file. Use the --debug flag to learn more.
    at PluginManager.resolveServicePlugins (file:///root/.serverless/releases/4.14.3/package/dist/sf-core.js:1241:2914)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async PluginManager.loadAllPlugins (file:///root/.serverless/releases/4.14.3/package/dist/sf-core.js:1241:1292)
    at async Serverless.init (file:///root/.serverless/releases/4.14.3/package/dist/sf-core.js:1248:9843)
    at async runFramework (file:///root/.serverless/releases/4.14.3/package/dist/sf-core.js:1275:839)
    at async TraditionalRunner.run (file:///root/.serverless/releases/4.14.3/package/dist/sf-core.js:1271:28313)
    at async route (file:///root/.serverless/releases/4.14.3/package/dist/sf-core.js:1302:2779)
    at async Object.run (file:///root/.serverless/releases/4.14.3/package/dist/sf-core.js:1303:3661)
    at async run2 (file:///root/.serverless/releases/4.14.3/package/dist/sf-core.js:1303:4815)
For help, try the following:
  • Run the command again with the "--debug" option
  • Run "serverless support"
  • Review the docs: https://www.serverless.com/framework/docs/

Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

### Environment information

```shell
Serverless Framework v4.14.3
Plugin version: tried with both 6.1.1 and 6.1.2

s:core: {
  node: 'v22.15.0',
  os: 'linux',
  arch: 'x64',
  shell: undefined,
  nodeJsPath: '/usr/local/bin/node',
  scriptPath: '/root/.serverless/releases/4.14.3/package/dist/sf-core.js',
  scriptArgs: [ 'deploy', '-s', 'sls-v4', '--debug' ],
  logLevel: 'debug',
  isInteractive: undefined
}
s:core: { serverless_framework: '4.14.3' }
Initializing
Initializing
s:core:router: {
  command: [ 'deploy' ],
  options: { s: 'sls-v4', debug: '*' },
  versions: { serverless_framework: '4.14.3' },
  compose: undefined
}
```
